# Generated by Django 2.2.2 on 2019-06-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test for the description aljoejalslfjojwsljfjewofj'),
            preserve_default=False,
        ),
    ]
